# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

# Speeding up a Visual Studio build.
# http://blogs.msdn.com/b/vcblog/archive/2011/01/05/damn-my-vc-project-is-building-slower-in-vs2010-what-do-i-do-now-a-step-by-step-guide.aspx
version: 'build-{build}-{branch}'

platform: x64

build:
  parallel: true

environment:
  # Create expected SHELL variable for pipenv.
  SHELL: "windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
      GENERATOR: "MSYS Makefiles"
      BUILDFLAGS: "VERBOSE=1"
      CMAKEARGS: ""
      ANACONDA_TESTS_ONLY: "1"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
      GENERATOR: "Visual Studio 14 2015 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
      GENERATOR: "MSYS Makefiles"
      BUILDFLAGS: "VERBOSE=1"
      CMAKEARGS: ""
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSYSTEM: MINGW64
      GENERATOR: "Visual Studio 15 2017 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
      GENERATOR: "Ninja"
      BUILDFLAGS: "-v"
      CMAKEARGS: ""
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MSYSTEM: MINGW64
      GENERATOR: "Visual Studio 14 2015 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
      ANACONDA_TESTS_ONLY: "1"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MSYSTEM: MINGW64
      GENERATOR: "Visual Studio 15 2017 Win64"
      BUILDFLAGS: "/verbosity:normal"
      CMAKEARGS: "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake"
      ANACONDA_TESTS_ONLY: "1"

#matrix:
#  fast_finish: true

init:
  - set PATH=C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%
  - set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%
  # Remove Python 2.7 from path
  - set PATH=%PATH:C:\Python27;=%
  - set PATH=%PATH:C:\Python27\Scripts;=%
  # Add Anaconda to PATH
  - set PATH=C:\Deps\conda\Scripts;C:\Deps\conda\library\bin;%PATH%

cache:
  - c:\msys64\var\cache\pacman\pkg -> testing\dependencies\appveyor\install.bat
  - c:\tools\vcpkg\installed\ -> testing\dependencies\appveyor\install.bat
  - c:\Deps\conda\ -> testing\dependencies\appveyor\anaconda.bat

install:
  - python -m pip install pipenv
  - '%APPVEYOR_BUILD_FOLDER%\testing\dependencies\appveyor\install.bat'
  - ps: .$env:APPVEYOR_BUILD_FOLDER\testing\dependencies\appveyor\anaconda.ps1
  - ps: .$env:APPVEYOR_BUILD_FOLDER\testing\dependencies\appveyor\install-msmpi.ps1

# extract step has to happen before the sh.exe workaround otherwise 7z will complain
before_build:
  - python --version
  - cmake --version
  - cd C:\projects
  - appveyor DownloadFile https://github.com/dev-cafe/cmake-cookbook/archive/%APPVEYOR_REPO_COMMIT%.zip
  - '%APPVEYOR_BUILD_FOLDER%\testing\dependencies\appveyor\extract.bat'

build_script:
  - bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv install"
  - if "%ANACONDA_TESTS_ONLY%"=="1" (
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-04'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-05'"
    ) else (
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-03'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-02'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-11/recipe-01'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-09/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-07/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-06/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-05/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-04/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-03/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-02/recipe-*'" &&
      bash -c "cd /c/projects/cmake-cookbook-no-symlinks && pipenv run python testing/collect_tests.py 'chapter-01/recipe-*'"
    )

deploy: off
